# Generated by Django 6.1 on 2026-08-25 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_on_posted', models.DateTimeField(auto_created=True)),
                ('AboutUs', models.CharField(blank=True, max_length=1000)),
                ('Description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='posts')),
                ('username', models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
