# Generated by Django 6.1 on 2026-08-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default/defaultProfile.jpg', upload_to='profiles'),
        ),
    ]
